name: sudoku_solver_application
description: Sudoku Solver APP

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5
  firebase_core: ^1.14.0
  firebase_storage: ^10.2.11
  uuid: ^3.0.6
  fluttertoast: ^8.0.9
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  animated_splash_screen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - images/


